### ISSUE TITLE
Example on the adult data does not work

### ISSUE THREAD

**Issue by lyesram** [leo-mazz/crowds#1]
Hi,

When I run this line of code : 

`anonymize(adult, generalization_rules=generalization_rules, k=10, max_sup=0.5, info_loss=dm_star_loss)`

The data structure returned by the algorithm is : 

> {'age': 0, 'sex': 0}]

**Comment by leo-mazz** [comment]
Hi,
What `anonymize` returns is actually a tuple, the first item being the result dataframe, and the second being what you post, i.e. the output generalization levels. I hope this helps, closing the issue unless you think something else in the output is incorrect.

**Comment by RunshanHu** [comment]
Hi,

I run the example with the following generalization rules:

def generalize_age(value):
    if value <= 1950:
        return 'quite old'
    if value > 1950 and value <= 1980:
        return 'a bit old'
    if value > 1980 and value <= 2000:
        return 'young'
    if value > 2000:
        return 'too young'

def generalize_sex(value):
    return 'People'

generalization_rules = {
    'age': GenRule([generalize_age]),   # 2-levels generalization
    'sex': GenRule([generalize_sex]),     # 1-level generalization
}

I print out the first returned result 'release' of the 'anonymize' function, however, nothing changed on both 'age' and 'sex' features.
